services:
  backend:
    build: .
    ports:
      - "3001:3001"
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: postgres
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER=elysia
      - POSTGRES_PASSWORD=elysia
      - POSTGRES_DB=elysia
    volumes:
      - elysia_pgdata:/var/lib/postgresql/data

volumes:
  elysia_pgdata:
    name: elysia_pgdata