### Register
POST http://localhost:3001/api/v1/register
Content-Type: application/json

{
    "name": "ihsan",
    "email": "ihsan2@mail.com",
    "password": "qwerty123"
}

### Login
POST http://localhost:3001/api/v1/login
Content-Type: application/json

{
    "email": "ihsan@mail.com",
    "password": "qwerty123"
}