### GET Todos
GET http://localhost:3001/todos?sort=asc&min=1&max=2

### GET Todos by ID
GET http://localhost:3001/todos/1

### POST Todos
POST http://localhost:3001/todos
Content-Type: application/json
Authorization: bearer Token

{
    "todo": "test 1 todos",
    "userId": 123
}